create table regions (
    id_region number generated by default as identity
                     (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30)
);

create table towns(
    id_town number generated by default as identity
                  (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30),
    id_region number references regions(id_region)
);

create table medical_organizations(
    id_medical_organization number generated by default as identity
                  (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30),
    id_town number references towns(id_town)
);

create table ages(
    id_age number generated by default as identity
                  (start with 1 maxvalue 99 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(20),
    min_age int,
    max_age int
);

create table genders(
    id_gender number generated by default as identity
                  (start with 1 maxvalue 9 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(10)
);

create table work_time(
    id_work_time number generated by default as identity
                  (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    start_mon date,
    end_mon date,
    start_tues date,
    end_tues date,
    start_wed date,
    end_wed date,
    start_thurs date,
    end_thurs date,
    start_fri date,
    end_fri date,
    start_sat date,
    end_sat date,
    start_sun date,
    end_sun date
);