create table regions (
    id_region number generated by default as identity
                     (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30)
);

create table towns(
    id_town number generated by default as identity
                  (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30),
    id_region number references regions(id_region)
)