create table regions (
    id_region number generated by default as identity
                     (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30) not null
);

create table towns(
    id_town number generated by default as identity
                  (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30) not null ,
    id_region number references regions(id_region)
);

create table medical_organizations(
    id_medical_organization number generated by default as identity
                  (start with 1 maxvalue 9999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(100) not null ,
    id_town number references towns(id_town)
);


create table ages(
    id_age number generated by default as identity
                  (start with 1 maxvalue 99 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(20) not null,
    min_age int not null,
    max_age int not null
);

create table genders(
    id_gender number generated by default as identity
                  (start with 1 maxvalue 9 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(10) not null
);

create table PEROV_VL.work_days(
      id_work_day number generated by default as identity
                  (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
      day varchar2(10) not null ,
      begin_time date null,
      end_time date null,
      id_hospital number references hospitals(id_hospital) not null
);

create table hospital_types(
    id_hospital_type number generated by default as identity
                  (start with 1 maxvalue 99 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(20) not null
);

create table hospital_status(
     id_status number generated by default as identity
                  (start with 1 maxvalue 99 minvalue 1 nocycle nocache noorder ) primary key,
     name varchar2(20) not null
);

create table PEROV_VL.hospitals(
    id_hospital number generated by default as identity
                  (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(100) not null ,
    id_medical_organization number references medical_organizations(id_medical_organization),
    id_hospital_type number references hospital_types(id_hospital_type),
    id_status number references hospital_status(id_status),
    date_delete date null
);

create table qualifications(
    id_qualification number generated by default as identity
                  (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(20) not null
);

create table ticket_status(
    id_ticket_status number generated by default as identity
                  (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(10) not null
);

create table specializations(
    id_specialization number generated by default as identity
                 (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30) not null ,
    id_age number references ages(id_age) not null ,
    date_delete date null
);

create table PEROV_VL.specializations_genders(
    id_specialization number references PEROV_VL.SPECIALIZATIONS(ID_SPECIALIZATION),
    id_gender number references PEROV_VL.GENDERS(ID_GENDER)
);

create table doctors(
    id_doctor number generated by default as identity
                 (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30),
    last_name varchar2(30),
    patronymic varchar2(30) null,
    id_hospital number references hospitals(id_hospital),
    id_qualification number references qualifications(id_qualification),
    number_area int,
    date_delete date
);

create table doctors_specializations(
    id_doctor number references doctors(id_doctor),
    id_specialization number references specializations(id_specialization)
);

create table accounts(
    id_account number generated by default as identity
                 (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    login varchar2(50) not null ,
    password varchar2(100) not null
);

create table patient(
    id_patient number generated by default as identity
                    (start with 1 maxvalue 9999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(30) not null ,
    last_name varchar2(30) not null ,
    patronymic varchar2(30) null,
    birth_date date not null ,
    number_area int not null ,
    id_gender number references genders(id_gender),
    id_account number references accounts(id_account),
    number_phone varchar2(15) not null
);

create table tickets(
    id_ticket number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) primary key,
    id_doctor number references doctors(id_doctor),
    id_status number references ticket_status(id_ticket_status),
    start_date timestamp not null ,
    end_date timestamp not null
);

create table record_status(
    id_status number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(10) not null
);

create table PEROV_VL.records(
    id_record number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) primary key,
    date_record date not null ,
    id_patient number references patient(id_patient) not null ,
    date_cancellation date null,
    id_status number references record_status(id_status) not null,
    id_ticket number references tickets(id_ticket) not null
);

create table PEROV_VL.documents(
    id_document number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(10) not null ,
    series_document int null,
    number_documents int not null,
    id_patient number references patient(id_patient) not null
);

create table PEROV_VL.educations(
    id_education number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(20) not null
);

create table PEROV_VL.doctors_educations(
    id_doctor number references PEROV_VL.doctors(id_doctor),
    id_education number references PEROV_VL.educations(id_education)
);

create table PEROV_VL.stars(
    id_stars number generated by default as identity
                    (start with 1 maxvalue 9 minvalue 1 nocycle nocache noorder ) primary key,
    name varchar2(20) not null,
    count_stars int not null check ( count_stars > 0 and count_stars < 6)
);

create table PEROV_VL.feedback(
    id_feedback number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) primary key,
    text_feedback varchar2(1000),
    id_stars number references PEROV_VL.stars(id_stars),
    id_doctor number references PEROV_VL.DOCTORS(id_doctor)
);

create table PEROV_VL.salary(
    id_salary number generated by default as identity
                    (start with 1 maxvalue 9999999999 minvalue 1 nocycle nocache noorder ) ,
    date_payment date not null,
    amount_salary int not null,
    id_doctor number references PEROV_VL.doctors(id_doctor)
);




